'use strict';
const services={corte_kids:{name:'Corte kids',price:45,minutes:30},primeiro_corte:{name:'Primeiro corte',price:55,minutes:45},corte_penteado:{name:'Corte + penteado',price:65,minutes:40}};
const professionals={lia:'Lia',caio:'Caio'};
const storageKey='pontoKidsBooking';
function readBooking(){try{return JSON.parse(sessionStorage.getItem(storageKey)||'null')}catch{return null}}
function valid(b){return b&&services[b.service]&&professionals[b.professional]&&/^\d{4}-\d{2}-\d{2}$/.test(b.day)&&['09:00','11:00','14:00','16:00'].includes(b.time)}
function summary(b){const s=services[b.service];const rows=[['Serviço',s.name],['Profissional',professionals[b.professional]],['Data',new Date(b.day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})],['Horário',b.time],['Duração',s.minutes+' minutos'],['Valor',s.price.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})]];const dl=document.createElement('dl');for(const [label,value] of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);dl.append(row)}document.getElementById('summary').replaceChildren(dl)}
const form=document.getElementById('booking');
if(form){const service=document.getElementById('service'),professional=document.getElementById('professional'),day=document.getElementById('day'),time=document.getElementById('time'),review=document.getElementById('review');for(let i=1;i<=3;i++){const d=new Date();d.setDate(d.getDate()+i);const value=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');day.add(new Option(d.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}),value))}const selected=new URLSearchParams(location.search).get('servico');if(services[selected])service.value=selected;let draft=null,confirmed=false;form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;draft={service:service.value,professional:professional.value,day:day.value,time:time.value};summary(draft);form.hidden=true;review.hidden=false;review.focus()});document.getElementById('edit').onclick=()=>{review.hidden=true;form.hidden=false;service.focus()};document.getElementById('confirm').onclick=()=>{if(confirmed||!valid(draft))return;try{sessionStorage.setItem(storageKey,JSON.stringify(draft));confirmed=true;document.getElementById('confirm').disabled=true;location.href='confirmacao.html'}catch{document.getElementById('error').textContent='Não foi possível continuar neste navegador. Permita o armazenamento da sessão e tente novamente.'}}}
if(document.getElementById('success')){const b=readBooking();if(valid(b)){summary(b);document.getElementById('success').hidden=false}else document.getElementById('empty').hidden=false;document.getElementById('new-booking').onclick=()=>{try{sessionStorage.removeItem(storageKey)}catch{}}}
